# version: '27.3'

services:
  db:
    container_name: parkify_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data_parkify:/var/lib/postgresql/data
volumes:
  db_data_parkify: